CREATE TABLE `home_visit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `encounter_uuid` char(38) NOT NULL,
  `home_visit_date` datetime NOT NULL,
  `form_id` int(11) DEFAULT NULL,
  `encounter_type` int(11) DEFAULT NULL,
  `patient_uuid` char(38) DEFAULT NULL,
  `encounter_created_date` datetime DEFAULT NULL,
  `encounter_change_date` datetime DEFAULT NULL,
  `location_uuid` char(38) DEFAULT NULL,
  `reason_visit_hivexposed_child` int(11) DEFAULT NULL,
  `reason_visit_pos_pcr` int(11) DEFAULT NULL,
  `reason_visit_tb_active` int(11) DEFAULT NULL,
  `reason_visit_ltfu` int(11) DEFAULT NULL,
  `reason_visit_high_vl` int(11) DEFAULT NULL,
  `reason_visit_therapeutic_failure` int(11) DEFAULT NULL,
  `reason_visit_defaulter` int(11) DEFAULT NULL,
  `reason_visit_iit` int(11) DEFAULT NULL,
  `reason_visit_prev_fup` int(11) DEFAULT NULL,
  `reason_visit_other` int(11) DEFAULT NULL,
  `phone_call_reintegration` int(11) DEFAULT NULL,
  `visit_type` int(11) DEFAULT NULL,
  `first_visit_found` int(11) DEFAULT NULL,
  `second_visit_date` datetime DEFAULT NULL,
  `second_visit_found` int(11) DEFAULT NULL,
  `third_visit_date` datetime DEFAULT NULL,
  `third_visit_found` int(11) DEFAULT NULL,
  `visit_number` int(11) DEFAULT NULL,
  `referred_health_facility` int(11) DEFAULT NULL,
  `patient_returned` int(11) DEFAULT NULL,
  `patient_returned_date` datetime DEFAULT NULL,
  `card_returned_date` datetime DEFAULT NULL,
  `source_database` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `home_visit_encounter_uuid` (`encounter_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
