DROP TABLE IF EXISTS `type_id_lookup`;

CREATE TABLE `type_id_lookup`(
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `table_name` varchar(255) DEFAULT NULL,
  `column_name` varchar(255) DEFAULT NULL,
  `id_type_lookup` varchar(11) DEFAULT NULL,
  `id_type_desc` varchar(255) DEFAULT NULL,
  `id_type_desc_pt` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `type_id_lookup`(`table_name`, `column_name`, `id_type_lookup`, `id_type_desc`, `id_type_desc_pt`, `notes`)
VALUES('form','form_id',60,'LABORATORIO GERAL-V2008','LABORATORIO GERAL-V2008','RETIRED'),
('form','form_id',62,'TARV: RASTREIO DE TUBERCULOSE','TARV: RASTREIO DE TUBERCULOSE','RETIRED'),
('form','form_id',99,'ADULTO: PROCESSO PARTE A - ANAMNESE - ','ADULTO: PROCESSO PARTE A - ANAMNESE - ','RETIRED'),
('form','form_id',100,'ADULTO: PROCESSO PARTE B - EXAME CLINICO','ADULTO: PROCESSO PARTE B - EXAME CLINICO','RETIRED '),
('form','form_id',101,'ADULTO: SEGUIMENTO - v2008','ADULTO: SEGUIMENTO - v2008','RETIRED '),
('form','form_id',103,'BUSCA ACTIVA','BUSCA ACTIVA','RETIRED '),
('form','form_id',105,'CCR: SEGUIMENTO','CCR: SEGUIMENTO',''),
('form','form_id',106,'LABORATORIO GERAL','LABORATORIO GERAL',''),
('form','form_id',108,'PEDIATRIA: PROCESSO PARTE A- ANAMNESE','PEDIATRIA: PROCESSO PARTE A- ANAMNESE','RETIRED'),
('form','form_id',109,'PEDIATRIA: PROCESSO PARTE B - EXAME CLINICO','PEDIATRIA: PROCESSO PARTE B - EXAME CLINICO','RETIRED'),
('form','form_id',110,'PEDIATRIA: SEGUIMENTO - v2008','PEDIATRIA: SEGUIMENTO - v2008','RETIRED'),
('form','form_id',115,'TARV: ACONSELHAMENTO','TARV: ACONSELHAMENTO','RETIRED'),
('form','form_id',116,'TARV: ACONSELHAMENTO SEGUIMENTO','TARV: ACONSELHAMENTO SEGUIMENTO','RETIRED'),
('form','form_id',117,'TARV: FRIDA - v2008','TARV: FRIDA - v2008','RETIRED'),
('form','form_id',118,'TARV: RASTREIO DE TUBERCULOSE','TARV: RASTREIO DE TUBERCULOSE','RETIRED'),
('form','form_id',119,'TARV: SOLICITACAO','TARV: SOLICITACAO','RETIRED'),
('form','form_id',120,'TUBERCULOSE: LIVRO','TUBERCULOSE: LIVRO','RETIRED'),
('form','form_id',121,'TARV: VISITA DOMICILIARIA ','TARV: VISITA DOMICILIARIA ',''),
('form','form_id',122,'CCU: RASTREIO','CCU: RASTREIO',''),
('form','form_id',123,'TARV: AVALICAO E PREPARACAO DO CANDIDATO AO TARV','TARV: AVALICAO E PREPARACAO DO CANDIDATO AO TARV','RETIRED'),
('form','form_id',124,'TARV: AVALIACAO DE ADESAO','TARV: AVALIACAO DE ADESAO','RETIRED'),
('form','form_id',125,'TARV: TERMO DE CONSENTIMENTO','TARV: TERMO DE CONSENTIMENTO','RETIRED'),
('form','form_id',126,'ADULTO: SEGUIMENTO - v2012','ADULTO: SEGUIMENTO - v2012','RETIRED'),
('form','form_id',127,'PEDIATRIA: SEGUIMENTO - v2012','PEDIATRIA: SEGUIMENTO - v2012','RETIRED '),
('form','form_id',128,'LIVRO DE REGISTO PRE-TARV','LIVRO DE REGISTO PRE-TARV','RETIRED '),
('form','form_id',129,'LIVRO DE REGISTO TARV','LIVRO DE REGISTO TARV','RETIRED '),
('form','form_id',130,'FILA','FILA',''),
('form','form_id',131,'TARV: AVALIACAO PSICOLOGICA E PP - INICIAL ','TARV: AVALIACAO PSICOLOGICA E PP - INICIAL ','RETIRED '),
('form','form_id',132,'TARV: AVALIACAO PSICOLOGICA E PP - SEGUIMENTO','TARV: AVALIACAO PSICOLOGICA E PP - SEGUIMENTO','RETIRED '),
('form','form_id',146,'CONSENTIMENTO DE TESTE DE CASO INDICE','CONSENTIMENTO DE TESTE DE CASO INDICE',''),
('form','form_id',147,'FSR','FSR',''),
('form','form_id',163,'FICHA MESTRA - FICHA CLINICA ','FICHA MESTRA - FICHA CLINICA ',''),
('form','form_id',164,'FICHA MESTRA - FICHA APSS E PP','FICHA MESTRA - FICHA APSS E PP',''),
('form','form_id',165,'FICHA MESTRA- FICHA RESUMO','FICHA MESTRA- FICHA RESUMO',''),
('form','form_id',166,'FICHA MESTRA - RECEPCAO - LEVANTOU TARV','FICHA MESTRA - RECEPCAO - LEVANTOU TARV',''),
('form','form_id',171,'FILT ','FILT ',''),
('form','form_id',172,'LIVRO DE REGISTO DIARIO DE CHAMADAS E VISITAS DOMICILIARES','LIVRO DE REGISTO DIARIO DE CHAMADAS E VISITAS DOMICILIARES',''),
('form','encounter_type',1,'S.TARV: ADULTO INICIAL B','S.TARV: ADULTO INICIAL B','RETIRED'),
('form','encounter_type',3,'S.TARV: PEDIATRIA INICIAL B','S.TARV: PEDIATRIA INICIAL B','RETIRED'),
('form','encounter_type',5,'S.TARV: ADULTO INICIAL A ','S.TARV: ADULTO INICIAL A ','RETIRED'),
('form','encounter_type',6,'S.TARV: ADULTO SEGUIMENTO','S.TARV: ADULTO SEGUIMENTO',' '),
('form','encounter_type',7,'S.TARV: PEDIATRIA INICIAL A ','S.TARV: PEDIATRIA INICIAL A ','RETIRED'),
('form','encounter_type',9,'S.TARV: PEDIATRIA SEGUIMENTO','S.TARV: PEDIATRIA SEGUIMENTO','RETIRED '),
('form','encounter_type',10,'CCR: SEGUIMENTO','CCR: SEGUIMENTO',''),
('form','encounter_type',11,'PTV: PRE-NATAL INICIAL','PTV: PRE-NATAL INICIAL','RETIRED '),
('form','encounter_type',13,'MISAU: LABORATORIO','MISAU: LABORATORIO',''),
('form','encounter_type',17,'S.TARV: SOLICITAÇÃO ARV','S.TARV: SOLICITAÇÃO ARV','RETIRED '),
('form','encounter_type',18,'S.TARV: FARMACIA ','S.TARV: FARMACIA ',''),
('form','encounter_type',19,'S.TARV: ACONSELHAMENTO','S.TARV: ACONSELHAMENTO','RETIRED'),
('form','encounter_type',20,'TUBERCULOSE: RASTREIO','TUBERCULOSE: RASTREIO','RETIRED'),
('form','encounter_type',21,'S.TARV: BUSCA ACTIVA ','S.TARV: BUSCA ACTIVA ',''),
('form','encounter_type',22,'CCR: PCR','CCR: PCR','RETIRED'),
('form','encounter_type',24,'S.TARV: ACONSELHAMENTO SEGUIMENTO','S.TARV: ACONSELHAMENTO SEGUIMENTO','RETIRED'),
('form','encounter_type',28,'CCU: RASTREIO','CCU: RASTREIO',''),
('form','encounter_type',29,'S.TARV: AVALIACAO E PREPARACAO DO CANDIDATO TARV','S.TARV: AVALIACAO E PREPARACAO DO CANDIDATO TARV','RETIRED'),
('form','encounter_type',30,'S.TARV: TERMO DE CONSENTIMENTO DE VISITA','S.TARV: TERMO DE CONSENTIMENTO DE VISITA','RETIRED'),
('form','encounter_type',31,'S.TARV: AVALIACAO DE ADESAO','S.TARV: AVALIACAO DE ADESAO','RETIRED'),
('form','encounter_type',32,'S.TARV: LIVRO PRE-TARV','S.TARV: LIVRO PRE-TARV','RETIRED'),
('form','encounter_type',33,'S.TARV: LIVRO TARV','S.TARV: LIVRO TARV','RETIRED'),
('form','encounter_type',34,'APSS: PREVENCAO POSITIVA - INICIAL ','APSS: PREVENCAO POSITIVA - INICIAL ','RETIRED'),
('form','encounter_type',35,'APSS: PREVENCAO POSITIVA - SEGUIMENTO ','APSS: PREVENCAO POSITIVA - SEGUIMENTO ',''),
('form','encounter_type',47,'RASTREIO FAMILIAR','RASTREIO FAMILIAR',''),
('form','encounter_type',51,'FSR - Carga Viral','FSR - Carga Viral',''),
('form','encounter_type',52,'FICHA MESTRA- LEVANTAMENTO DE ARV ','FICHA MESTRA- LEVANTAMENTO DE ARV ',''),
('form','encounter_type',53,'FICHA MESTRA - FICHA RESUMO ','FICHA MESTRA - FICHA RESUMO ',''),
('form','encounter_type',60,'TRATAMENTO PROFILATICO DA TUBERCULOSE (TPT)','TRATAMENTO PROFILATICO DA TUBERCULOSE (TPT)',''),
('identifier','identifier_type',1,'OPEN MRS ID ','OPEN MRS ID ',''),
('identifier','identifier_type',2,'NID - SERVICO TARV ','NID - SERVICO TARV ',''),
('identifier','identifier_type',5,'CODIGO ATS/UATS','CODIGO ATS/UATS',''),
('identifier','identifier_type',6,'CODIGO PTV (PRE-NATAL)','CODIGO PTV (PRE-NATAL)',''),
('identifier','identifier_type',7,'CODIGO ITS','CODIGO ITS',''),
('identifier','identifier_type',8,'CODIGO PTV (MATERNIDADE)','CODIGO PTV (MATERNIDADE)',''),
('identifier','identifier_type',9,'NID (CCR)','NID (CCR)',''),
('identifier','identifier_type',10,'PCR (NUMERO DE REGISTO)','PCR (NUMERO DE REGISTO)',''),
('identifier','identifier_type',11,'NIT (SECTOR DE TB)','NIT (SECTOR DE TB)',''),
('identifier','identifier_type',12,'NUMERO CANCRO CERVICAL','NUMERO CANCRO CERVICAL',''),
('identifier','identifier_type',15,'DISA NID','DISA NID',''),
('identifier','identifier_type',16,'CRAM ID ','CRAM ID ',''),
('identifier','identifier_type',17,'NID PREP','NID PREP',''),
('patient','birthdate_estimated ',1,'YES, DATE OF BIRTH IS ESTIMATED','SIM, DATA DE NASCIMENTO ESTIMADA',''),
('patient','birthdate_estimated ',0,'NO, DATE OF BIRTH IS NOT ESTIMATED','NÃO, DATA DE NASCIMENTO NÃO FOI ESTIMADA',''),
('patient_state','program_id',1,'SERVICO TARV - CUIDADO','SERVICO TARV - CUIDADO',''),
('patient_state','program_id',2,'SERVICO TARV - TRATAMENTO','SERVICO TARV - TRATAMENTO',''),
('patient_state','program_id',5,'TUBERCULOSE','TUBERCULOSE',''),
('patient_state','program_id',6,'CCR','CCR',''),
('patient_state','program_id',7,'CCU','CCU',''),
('patient_state','program_id',8,'PTV/ETV','PTV/ETV',''),
('patient_state','program_id',9,'CLINICA MOVEL','CLINICA MOVEL',''),
('patient_state','program_id',25,'PREP','PREP',''),
('patient_state','source_id',1,'SERVICO TARV - CUIDADO','SERVICO TARV - CUIDADO',''),
('patient_state','source_id',2,'SERVICO TARV - TRATAMENTO','SERVICO TARV - TRATAMENTO',''),
('patient_state','source_id',5,'TUBERCULOSE','TUBERCULOSE',''),
('patient_state','source_id',6,'CCR','CCR',''),
('patient_state','source_id',7,'CCU','CCU',''),
('patient_state','source_id',8,'PTV/ETV','PTV/ETV',''),
('patient_state','source_id',9,'CLINICA MOVEL','CLINICA MOVEL',''),
('patient_state','source_id',25,'PREP','PREP',''),
('patient_state','source_id',0,'DEMOGRAPHIC','DEMOGRAFICO',''),
('patient_state','source_id',165,'FICHA RESUMO','FICHA RESUMO',''),
('patient_state','source_id',163,'FICHA CLINICA','FICHA CLINICA',''),
('patient_state','source_id',121,'TARV: VISITA DOMICILIARIA','TARV: VISITA DOMICILIARIA',''),
('patient_state','state_id',50,'ABORTION','ABORTO',''),
('patient_state','state_id',1256,'START','INÍCIO',''),
('patient_state','state_id',1366,'DIED','ÓBITO',''),
('patient_state','state_id',1369,'TRANSFERRED IN','TRANSFERIDO DE',''),
('patient_state','state_id',1705,'RESTART','REINÍCIO',''),
('patient_state','state_id',1706,'TRANSFERRED OUT','TRANSFERIDO PARA',''),
('patient_state','state_id',1707,'DROPPED FROM TREATMENT','ABANDONO',''),
('patient_state','state_id',1709,'SUSPEND TREATMENT ','SUSPENSO',''),
('patient_state','state_id',1798,'MEDICAL CONSULTATION','CONSULTA MÉDICA',''),
('patient_state','state_id',1982,'PREGNANT','GRÁVIDA',''),
('patient_state','state_id',6248,'BIRTH','NASCIMENTO',''),
('patient_state','state_id',6269,'ACTIVE ','ACTIVO',''),
('patient_state','state_id',6301,'CURED','CURADO',''),
('patient_state','state_id',6302,'TB CURED','TB CURADO',''),
('patient_state','state_id',23903,'HIV NEGATIVE','HIV NEGATIVO',''),
('patient_state','state_id',23863,'AUTO TRANSFERENCE','AUTO TRANSFERENCIA',''),
('patient_state','state_id',165231,'EXIT - HIV POSITIVE TESTED','SAÍDA – TESTADO HIV POSITIVO',''),
('patient_state','state_id',165232,'EXIT - NO MORE SUBSTANTIAL RISKS','SAÍDA – SEM MAIS RISCO SUBSTANCIAL',''),
('patient_state','state_id',165233,'EXIT- SIDE EFFECTS','SAÍDA – EFEITOS SECUNDÁRIOS',''),
('patient_state','state_id',165234,'EXIT - USER PREFERENCE','SAÍDA – PREFERENCIA DO UTENTE',''),
('clinical_consultation','who_staging',1204,'I','I',''),
('clinical_consultation','who_staging',1205,'II','II',''),
('clinical_consultation','who_staging',1206,'III','III',''),
('clinical_consultation','who_staging',1207,'IV','IV',''),
('clinical_consultation','nutritional_grade',23754,'BMI/AGE','IMC/IDADE',''),
('clinical_consultation','nutritional_grade',23756,'P/E','P/E',''),
('clinical_consultation','nutritional_grade',1342,'BMI','IMC',''),
('clinical_consultation','nutritional_grade',1343,'BP','PB',''),
('medication','regimen_id',1703,'AZT+3TC+EFV','AZT+3TC+EFV',''),
('medication','regimen_id',6100,'AZT+3TC+LPV/r','AZT+3TC+LPV/r',''),
('medication','regimen_id',1651,'AZT+3TC+NVP','AZT+3TC+NVP',''),
('medication','regimen_id',6324,'TDF+3TC+EFV','TDF+3TC+EFV',''),
('medication','regimen_id',6104,'ABC+3TC+EFV','ABC+3TC+EFV',''),
('medication','regimen_id',23784,'TDF+3TC+DTG','TDF+3TC+DTG',''),
('medication','regimen_id',23785,'TDF+3TC+DTG','TDF+3TC+DTG',''),
('medication','regimen_id',23786,'ABC+3TC+DTG','ABC+3TC+DTG',''),
('medication','regimen_id',6116,'AZT+3TC+ABC','AZT+3TC+ABC',''),
('medication','regimen_id',6106,'ABC+3TC+LPV/r','ABC+3TC+LPV/r',''),
('medication','regimen_id',6105,'ABC+3TC+NVP','ABC+3TC+NVP',''),
('medication','regimen_id',6108,'TDF+3TC+LPV/r','TDF+3TC+LPV/r',''),
('medication','regimen_id',6424,'TDF+3TC+LPV/r','TDF+3TC+LPV/r',''),
('medication','regimen_id',23790,'TDF+3TC+LPV/r+RTV','TDF+3TC+LPV/r+RTV',''),
('medication','regimen_id',23791,'TDF+3TC+ATV/r','TDF+3TC+ATV/r',''),
('medication','regimen_id',23792,'ABC+3TC+ATV/r','ABC+3TC+ATV/r',''),
('medication','regimen_id',23793,'AZT+3TC+ATV/r','AZT+3TC+ATV/r',''),
('medication','regimen_id',23795,'ABC+3TC+ATV/r+RAL','ABC+3TC+ATV/r+RAL',''),
('medication','regimen_id',23796,'TDF+3TC+ATV/r+RAL','TDF+3TC+ATV/r+RAL',''),
('medication','regimen_id',23801,'AZT+3TC+RAL','AZT+3TC+RAL',''),
('medication','regimen_id',23802,'AZT+3TC+DRV/r','AZT+3TC+DRV/r',''),
('medication','regimen_id',23815,'AZT+3TC+DTG','AZT+3TC+DTG',''),
('medication','regimen_id',6329,'TDF+3TC+RAL+DRV/r','TDF+3TC+RAL+DRV/r',''),
('medication','regimen_id',23797,'ABC+3TC+DRV/r+RAL','ABC+3TC+DRV/r+RAL',''),
('medication','regimen_id',23798,'3TC+RAL+DRV/r','3TC+RAL+DRV/r',''),
('medication','regimen_id',23803,'AZT+3TC+RAL+DRV/r','AZT+3TC+RAL+DRV/r',''),
('medication','regimen_id',6243,'TDF+3TC+NVP','TDF+3TC+NVP',''),
('medication','regimen_id',6103,'D4T+3TC+LPV/r','D4T+3TC+LPV/r',''),
('medication','regimen_id',792,'D4T+3TC+NVP','D4T+3TC+NVP',''),
('medication','regimen_id',1827,'D4T+3TC+EFV','D4T+3TC+EFV',''),
('medication','regimen_id',6102,'D4T+3TC+ABC','D4T+3TC+ABC',''),
('medication','regimen_id',1311,'ABC+3TC+LPV/r','ABC+3TC+LPV/r',''),
('medication','regimen_id',1312,'ABC+3TC+NVP','ABC+3TC+NVP',''),
('medication','regimen_id',1313,'ABC+3TC+EFV','ABC+3TC+EFV',''),
('medication','regimen_id',1314,'AZT+3TC+LPV/r','AZT+3TC+LPV/r',''),
('medication','regimen_id',1315,'TDF+3TC+EFV','TDF+3TC+EFV',''),
('medication','regimen_id',6330,'AZT+3TC+RAL+DRV/r','AZT+3TC+RAL+DRV/r',''),
('medication','regimen_id',6325,'D4T+3TC+ABC+LPV/r','D4T+3TC+ABC+LPV/r',''),
('medication','regimen_id',6326,'AZT+3TC+ABC+LPV/r','AZT+3TC+ABC+LPV/r',''),
('medication','regimen_id',6327,'D4T+3TC+ABC+EFV','D4T+3TC+ABC+EFV',''),
('medication','regimen_id',6328,'AZT+3TC+ABC+EFV','AZT+3TC+ABC+EFV',''),
('medication','regimen_id',6109,'AZT+DDI+LPV/r','AZT+DDI+LPV/r',''),
('medication','regimen_id',21163,'AZT+3TC+LPV/r','AZT+3TC+LPV/r',''),
('medication','regimen_id',23799,'TDF+3TC+DTG','TDF+3TC+DTG',''),
('medication','regimen_id',23800,'ABC+3TC+DTG','ABC+3TC+DTG',''),
('medication','regimen_id',6110,'D4T20+3TC+NVP','D4T20+3TC+NVP',''),
('medication','regimen_id',1702,'AZT+3TC+NFV','AZT+3TC+NFV',''),
('medication','regimen_id',817,'AZT+3TC+ABC','AZT+3TC+ABC',''),
('medication','regimen_id',6244,'AZT+3TC+RTV','AZT+3TC+RTV',''),
('medication','regimen_id',1700,'AZT+DDl+NFV','AZT+DDl+NFV',''),
('medication','regimen_id',633,'EFV','EFV',''),
('medication','regimen_id',625,'D4T','D4T',''),
('medication','regimen_id',631,'NVP','NVP',''),
('medication','regimen_id',628,'3TC','3TC',''),
('medication','regimen_id',635,'NFV','NFV',''),
('medication','regimen_id',797,'AZT','AZT',''),
('medication','regimen_id',814,'ABC','ABC',''),
('medication','regimen_id',6107,'TDF+AZT+3TC+LPV/r','TDF+AZT+3TC+LPV/r',''),
('medication','regimen_id',6236,'D4T+DDI+RTV-IP','D4T+DDI+RTV-IP',''),
('medication','regimen_id',1701,'ABC+DDI+NFV','ABC+DDI+NFV',''),
('medication','regimen_id',6114,'3DFC','3DFC',''),
('medication','regimen_id',6115,'DFC+EFV','DFC+EFV',''),
('medication','regimen_id',6233,'AZT+3TC+DDI+LPV','AZT+3TC+DDI+LPV',''),
('medication','regimen_id',6234,'ABC+TDF+LPV','ABC+TDF+LPV',''),
('medication','regimen_id',6242,'D4T+DDI+NVP','D4T+DDI+NVP',''),
('medication','regimen_id',6118,'DI50+ABC+LPV','DI50+ABC+LPV',''),
('medication','regimen_id',23787,'ABC+AZT+LPV/r','ABC+AZT+LPV/r',''),
('medication','regimen_id',5424,'OTHER','OTHER',''),
('medication','formulation_id',11,'[TDF/3TC/DTG] Tenofovir 300mg/Lamivudine 300mg/Dolutegravir 50mg TLD30','[TDF/3TC/DTG] Tenofovir 300mg/Lamivudina 300mg/Dolutegravir 50mg TLD30',''),
('medication','formulation_id',12,'[TDF/3TC/DTG] Tenofovir 300mg/Lamivudine 300mg/Dolutegravir 50mg TLD90','[TDF/3TC/DTG] Tenofovir 300mg/Lamivudina 300mg/Dolutegravir 50mg TLD90',''),
('medication','formulation_id',13,'[TDF/3TC/DTG] Tenofovir 300mg/Lamivudine 300mg/Dolutegravir 50mg TLD180','[TDF/3TC/DTG] Tenofovir 300mg/Lamivudina 300mg/Dolutegravir 50mg TLD180',''),
('medication','formulation_id',17,'[LPV/RTV] Lopinavir/Ritonavir -Aluvia 200mg/50mg','[LPV/RTV] Lopinavir/Ritonavir -Aluvia 200mg/50mg',''),
('medication','formulation_id',18,'[ABC/3TC] Abacavir 600mg/Lamivudine 300mg','[ABC/3TC] Abacavir 600mg/Lamivudina 300mg',''),
('medication','formulation_id',19,'[DTG] Dolutegravir 50mg','[DTG] Dolutegravir 50mg',''),
('medication','formulation_id',20,'[ABC/3TC] Abacavir 120mg/Lamivudine 60mg','[ABC/3TC] Abacavir 120mg/Lamivudina 60mg',''),
('medication','formulation_id',21,'[ABC/3TC] Abacavir 60 and Lamivudine 30mg','[ABC/3TC] Abacavir 60 and Lamivudina 30mg',''),
('medication','formulation_id',22,'[3TC/AZT] Lamivudine 150mg/ Zidovudine 300mg','[3TC/AZT] Lamivudina 150mg/ Zidovudina 300mg',''),
('medication','formulation_id',23,'[3TC/AZT] Lamivudine 30mg/ Zidovudine 60mg','[3TC/AZT] Lamivudina 30mg/ Zidovudina 60mg',''),
('medication','formulation_id',24,'[TDF/3TC] Tenofovir 300mg/Lamivudine 300mg','[TDF/3TC] Tenofovir 300mg/Lamivudina 300mg',''),
('medication','formulation_id',25,'[RAL] Raltegravir 400mg','[RAL] Raltegravir 400mg',''),
('medication','formulation_id',26,'[LPV/RTV] Lopinavir/Ritonavir 400mg/100mg','[LPV/RTV] Lopinavir/Ritonavir 400mg/100mg',''),
('medication','formulation_id',27,'[LPV/RTV] Lopinavir/Ritonavir -Aluvia 100mg/25mg','[LPV/RTV] Lopinavir/Ritonavir -Aluvia 100mg/25mg',''),
('medication','formulation_id',28,'[LPV/RTV] Lopinavir/Ritonavir 200mg/50mg','[LPV/RTV] Lopinavir/Ritonavir 200mg/50mg',''),
('medication','formulation_id',29,'[LPV/RTV] Lopinavir/Ritornavir 40mg/10mg Pellets/Granules','[LPV/RTV] Lopinavir/Ritornavir 40mg/10mg Pellets/Granulos',''),
('medication','formulation_id',30,'[LPV/RTV]  Lopinavir/Ritonavir-Kaletra 80/20 mg/ml','[LPV/RTV]  Lopinavir/Ritonavir-Kaletra 80/20 mg/ml',''),
('medication','formulation_id',31,'[ATV/RTV] Atazanavir 300mg/Ritonavir 100mg','[ATV/RTV] Atazanavir 300mg/Ritonavir 100mg',''),
('medication','formulation_id',32,'[NVP] Nevirapine 200mg','[NVP] Nevirapina 200mg',''),
('medication','formulation_id',33,'[NVP]  Nevirapine 50mg','[NVP]  Nevirapina 50mg',''),
('medication','formulation_id',34,'[NVP] Nevirapine 50mg/5ml','[NVP] Nevirapina 50mg/5ml',''),
('medication','formulation_id',35,'[AZT] Zidovudine 50mg/5ml','[AZT] Zidovudina 50mg/5ml',''),
('medication','formulation_id',36,'[AZT] Zidovudine 300mg','[AZT] Zidovudina 300mg',''),
('medication','formulation_id',37,'[ABC] Abacavir 300mg','[ABC] Abacavir 300mg',''),
('medication','formulation_id',38,'[ABC] Abacavir 60mg','[ABC] Abacavir 60mg',''),
('medication','formulation_id',39,'[EFV] Efavirenz 600mg','[EFV] Efavirenz 600mg',''),
('medication','formulation_id',40,'[EFV] Efavirenz 200mg','[EFV] Efavirenz 200mg',''),
('medication','formulation_id',41,'[3TC] Lamivudine150mg','[3TC] Lamivudina150mg',''),
('medication','formulation_id',42,'[TDF] Tenofovir 300mg','[TDF] Tenofovir 300mg',''),
('medication','formulation_id',43,'[TDF/3TC/EFV] Tenofovir 300mg/Lamivudine 300mg/Efavirenz 400mg TLE90','[TDF/3TC/EFV] Tenofovir 300mg/Lamivudina 300mg/Efavirenz 400mg TLE90',''),
('medication','formulation_id',44,'[TDF/3TC/EFV] Tenofovir 300mg/Lamivudine 300mg/Efavirenz 400mg TLE30','[TDF/3TC/EFV] Tenofovir 300mg/Lamivudina 300mg/Efavirenz 400mg TLE30',''),
('medication','formulation_id',45,'[TDF/3TC/EFV] Tenofovir 300mg/Lamivudine 300mg/Efavirenz 400mg TLE180','[TDF/3TC/EFV] Tenofovir 300mg/Lamivudina 300mg/Efavirenz 400mg TLE180',''),
('medication','formulation_id',46,'[TDF/3TC/EFV] Tenofovir 300mg/Lamivudine 300mg/Efavirenz 600mg','[TDF/3TC/EFV] Tenofovir 300mg/Lamivudina 300mg/Efavirenz 600mg',''),
('medication','formulation_id',47,'[3TC/AZT/NVP] Lamivudine 150mg/Zidovudine 300mg/Nevirapine 200mg','[3TC/AZT/NVP] Lamivudina 150mg/Zidovudina 300mg/Nevirapina 200mg',''),
('medication','formulation_id',48,'[3TC/AZT/NVP] Lamivudine 30mg/Zidovudine 60mg/Nevirapine 50mg','[3TC/AZT/NVP] Lamivudina 30mg/Zidovudina 60mg/Nevirapina 50mg',''),
('medication','formulation_id',49,'[3TC/AZT/ABC] Lamivudine 150mg/Zidovudine 300mg/Abacavir 300mg','[3TC/AZT/ABC] Lamivudina 150mg/Zidovudina 300mg/Abacavir 300mg',''),
('medication','formulation_id',50,'[TDF/FTC] Tenofovir 300mg/Emtricitabine 200mg','[TDF/FTC] Tenofovir 300mg/Emtricitabina 200mg',''),
('medication','formulation_id',51,'[DTG] Dolutegravir 10 mg 90 Comp','[DTG] Dolutegravir 10 mg 90 Comp',''),
('medication','formulation_id',52,'[DTG] Dolutegravir 10 mg 30 Comp','[DTG] Dolutegravir 10 mg 30 Comp',''),
('medication','formulation_id',53,'[ABC/3TC] Abacavir 120mg/Lamivudine 60mg 30 Comp','[ABC/3TC] Abacavir 120mg/Lamivudina 60mg 30 Comp',''),
('medication','mode_dispensation_id',165175,'NORMAL EXPEDIENT SCHEDULE','HORÁRIO NORMAL DO EXPEDIENTE',''),
('medication','mode_dispensation_id',165176,'OUT OF TIME','FORA DO HORÁRIO',''),
('medication','mode_dispensation_id',165177,'FARMAC/PRIVATE PHARMACY','FARMÁCIA PRIVADA',''),
('medication','mode_dispensation_id',165178,'COMMUNITY DISPENSE VIA PROVIDER','DISPENSA COMUNITÁRIA VIA PROVEDOR',''),
('medication','mode_dispensation_id',165179,'COMMUNITY DISPENSE VIA APE','DISPENSA COMUNITÁRIA APE',''),
('medication','mode_dispensation_id',165180,'DAILY MOBILE BRIGADES','BRIGADAS MÓVEIS DIÚRNAS',''),
('medication','mode_dispensation_id',165181,'NIGHT MOBILE BRIGADES (HOTSPOTS)','BRIGADAS MÓVEIS NOTURNAS',''),
('medication','mode_dispensation_id',165182,'DAILY MOBILE CLINICS','CLÍNICAS MÓVEIS DIÚRNAS',''),
('medication','mode_dispensation_id',165183,'NIGHT MOBILE CLINICS (HOTSPOTS)','CLÍNICAS MÓVEIS NOTURNAS',''),
('medication','med_sequence_id',21150,'FIRST LINE','PRIMEIRA LINHA',''),
('medication','med_sequence_id',21148,'SECOND LINE','SEGUNDA LINHA',''),
('medication','med_sequence_id',21149,'THIRD LINE','TERCEIRA LINHA',''),
('medication','med_sequence_id',23741,'ALTERNATIVE 1st LINE OF THE ART','ALTERNATIVA A PRIMEIRA LINHA',''),
('medication','med_sequence_id',23893,'FIRST LINE','PRIMEIRA LINHA',''),
('medication','med_sequence_id',21190,'ALTERNATIVE 1st LINE OF THE ART','ALTERNATIVA A PRIMEIRA LINHA',''),
('medication','med_sequence_id',21187,'SECOND LINE','SEGUNDA LINHA',''),
('medication','med_sequence_id',21188,'THIRD LINE','TERCEIRA LINHA',''),
('medication','type_dispensation_id',1098,'MONTHLY','MENSAL',''),
('medication','type_dispensation_id',23720,'QUARTERLY','TRIMESTRAL',''),
('medication','type_dispensation_id',23888,'SEMESTER ','SEMESTRAL',''),
('medication','type_dispensation_id',165314,'ANNUAL','ANUAL',''),
('medication','alternative_line_id',1066,'NO','NÃO',''),
('medication','alternative_line_id',1371,'REGIMEN SWITCH','MUDANÇA DE LINHA',''),
('medication','alternative_line_id',23741,'ALTERNATIVE 1st LINE OF THE ART','ALTERNATIVA A PRIMEIRA LINHA',''),
('medication','reason_change_regimen_id',102,'TOXICITY','TOXICIDADE',''),
('medication','reason_change_regimen_id',1982,'PREGNANT','GRÁVIDA',''),
('medication','reason_change_regimen_id',1368,'PREGNANT RISK','RISCO DE GRAVIDEZ',''),
('medication','reason_change_regimen_id',1113,'TB DRUG START','INÍCIO DE TB',''),
('medication','reason_change_regimen_id',23744,'NEW MEDICATION AVAILABLE','NOVO MEDICAMENTO DISPONÍVEL',''),
('medication','reason_change_regimen_id',23745,'ART STOCK BREAK','ROPTURA DE STOCK DE ARV',''),
('medication','reason_change_regimen_id',1790,'CLINICAL FAILURE','FALÊNCIA CLÍNICA',''),
('medication','reason_change_regimen_id',1791,'IMMUNOLOGICAL FAILURE','FALÊNCIA IMUNOLOGICA',''),
('medication','reason_change_regimen_id',23746,'VIROLOGICAL FAULT','FALÊNCIA VIROLÓGICA',''),
('medication','med_side_effects_id',151,'ABDOMINAL PAIN','DOR ABDOMINAL',''),
('medication','med_side_effects_id',14475,'Nausea and Vomiting','NÁUSEAS E VÓMITOS',''),
('medication','med_side_effects_id',16,'DIARRHEA','DIARREIA',''),
('medication','med_side_effects_id',6295,'PSYCHOLOGICAL CHANGES','ALTERAÇÕES PSICOLÓGICAS',''),
('medication','med_side_effects_id',821,'PERIPHERAL NEUROPATHY','NEUROPATIA PERIFÉRICA',''),
('medication','med_side_effects_id',11428,'GENERALIZED SKIN RASH','Erupção cutânea generalizada',''),
('medication','med_side_effects_id',14671,'Hyperglycaemia','Hiperglicemia ',''),
('medication','med_side_effects_id',23747,'DYSLIPIDEMIA','DISLIPIDEMIA',''),
('medication','med_side_effects_id',6298,'LIPODYSTROPHY','LIPODISTROFIA',''),
('medication','med_side_effects_id',23748,'CYTOPENIA','CITOPENIA',''),
('medication','med_side_effects_id',6293,'PANCREATITIS','PANCREATITE',''),
('medication','med_side_effects_id',23749,'NEPHROTOXICITY','NEFROTOXICIDADE',''),
('medication','med_side_effects_id',29,'HEPATITIS','HEPATITE',''),
('medication','med_side_effects_id',23750,'STEVENS-JOHNSON SYNDROME','SINDROME DE STEVENS-JOHNSON',''),
('medication','med_side_effects_id',23751,'HYPERSENSITIVITY TO ABC/RAL','HIPERSENSIBILIDADE A ABC/RAL',''),
('medication','med_side_effects_id',6299,'LACTIC ACIDOSIS','ACIDOSE LACTICA',''),
('medication','med_side_effects_id',23752,'HEPATIC STEATOSIS WITH HYPERLACTATEMIA','ESTEATOSE HEPATICA COM HIPERLACTEMIA',''),
('medication','adherence_id',1383,'GOOD','BOM',''),
('medication','adherence_id',1749,'ARV ADHERENCE RISK','RISCO DE ADESÃO',''),
('medication','adherence_id',1385,'BAD','MAU',''),
('dsd','dsd_id',23730,'QUARTERLY DISPENSATION (DT)','DISPENSA TRIMESTRAL',''),
('dsd','dsd_id',23888,'SEMESTER ARV PICKUP','DISPENSA SEMESTRAL',''),
('dsd','dsd_id',165314,'ARV ANUAL DISPENSATION','DISPENSA ANUAL',''),
('dsd','dsd_id',165315,'DECENTRALIZED ARV DISPENSATION','DISPENSA DESCENTRALIZADA',''),
('dsd','dsd_id',165178,'COMMUNITY DISPENSE VIA PROVIDER','DISPENSA COMUNITÁRIA VIA PROVEDOR',''),
('dsd','dsd_id',165179,'COMMUNITY DISPENSE VIA APE','DISPENSA COMUNITÁRIA VIA APE',''),
('dsd','dsd_id',165264,'MOBILE BRIGADES','BRIGADAS MÓVEIS',''),
('dsd','dsd_id',165265,'MOBILE CLINICS','CLÍNICA MÓVEL',''),
('dsd','dsd_id',23725,'FAMILY APPROACH','ABORDAGEM FAMILIAR',''),
('dsd','dsd_id',23729,'RAPID FLOW (FR)','FLUXO RÁPIDO',''),
('dsd','dsd_id',23724,'GAAC','GAAC',''),
('dsd','dsd_id',23726,'ACCESSION CLUBS (CA)','CLUBES DE ADESÃO',''),
('dsd','dsd_id',165316,'HOURS EXTENSION','EXTENSÃO DE HORÁRIO',''),
('dsd','dsd_id',165317,'SINGLE STOP IN TB SECTOR','PARAGEM ÚNICA DE TB',''),
('dsd','dsd_id',165318,'SINGLE STOP ON TARV SERVICES','PARAGEM ÚNICA DE TARV',''),
('dsd','dsd_id',165319,'SINGLE STOP SAAJ','PARAGEM ÚNICA DE SAAJ',''),
('dsd','dsd_id',165320,'SINGLE STOP SMI','PARAGEM ÚNICA DE SMI',''),
('dsd','dsd_id',165321,'HIV ADVANCED DISEASE','DAH',''),
('dsd','dsd_id',23727,'SINGLE STOP (PU)','PARAGEM ÚNICA',''),
('dsd','dsd_id',23731,'COMMUNITY DISPENSATION (DC)','DISPENSA COMUNITÁRIA',''),
('dsd','dsd_id',165340,'BIMONTHLY DISPENSATION','DISPENSA BIMENSAL',''),
('dsd','dsd_state_id',1256,'START','INÍCIO',''),
('dsd','dsd_state_id',1257,'CONTINUE','CONTINUA',''),
('dsd','dsd_state_id',1267,'COMPLETED','FIM',''),
('keypop_vulnerable_pop','pop_type',23703,'KEY POPULATION','POPULAÇÃO CHAVE',''),
('keypop_vulnerable_pop','pop_type',23710,'VULNERABLE PEOPLE','POPULAÇÃO VULNERÁVEL',''),
('keypop_vulnerable_pop','pop_id',1377,'MEN WHO HAVE SEX WITH MEN','HOMEN QUE FAZ SEXO COM HOMEN',''),
('keypop_vulnerable_pop','pop_id',20454,'DRUG USE','USUÁRIO DE DROGA',''),
('keypop_vulnerable_pop','pop_id',20426,'IMPRISONMENT AND OTHER INCARCERATION','RECLUSO',''),
('keypop_vulnerable_pop','pop_id',1901,'SEX WORKER','TRABALHADOR DE SEXO',''),
('keypop_vulnerable_pop','pop_id',5622,'OTHER ','OUTRO',''),
('keypop_vulnerable_pop','pop_id',23885,' KEY POPULATION - OTHERS','POPULAÇÃO CHAVE - OUTROS',''),
('keypop_vulnerable_pop','pop_id',23711,'GIRL BETWEEN 10-14 YEARS','RAPARIGA ENTRE 10-14 ANOS',''),
('keypop_vulnerable_pop','pop_id',23712,'YOUNG WOMAN BETWEEN 15-24 YEARS','MULHERES JOVENS ENTRE 15-24 ANOS',''),
('keypop_vulnerable_pop','pop_id',1995,'THE COUPLES RESULTS ARE DIFFERENT','CASAIS SERODISCORDANTES',''),
('keypop_vulnerable_pop','pop_id',1977,'ASSOCIATION OF PEOPLE WITH HIV','PESSOAS VIVENDO COM HIV',''),
('keypop_vulnerable_pop','pop_id',1174,'ORPHAN','ÓRFÃO',''),
('keypop_vulnerable_pop','pop_id',23713,'PERSON WITH DISABILITY','PESSOA COM DEFICIÊNCIA',''),
('keypop_vulnerable_pop','pop_id',1908,'MINER','MINEIRO',''),
('keypop_vulnerable_pop','pop_id',1903,'DRIVER','MOTORISTA',''),
('keypop_vulnerable_pop','pop_id',1904,'MIGRANT WORKER','TRABALHADOR MIGRANTE',''),
('keypop_vulnerable_pop','pop_id',23890,'SEASONAL WORKERS','TRABALHADOR SAZONAL',''),
('laboratory','lab_test_id',856,'HIV VIRAL LOAD','CARGA VIRAL',''),
('laboratory','lab_test_id',1305,'VIRAL LOAD - QUAL','CARGA VIRAL QUALITATIVA',''),
('laboratory','lab_test_id',1695,'CD4 COUNT','CD4 ABSOLUTO',''),
('laboratory','lab_test_id',5497,'CD4 COUNT','CD4 ABSOLUTO',''),
('laboratory','lab_test_id',23896,'CD4 COUNT','CD4 ABSOLUTO',''),
('laboratory','lab_test_id',730,'CD4%','CD4%',''),
('laboratory','lab_test_id',1030,'HIV PCR TEST','TESTE DE PCR',''),
('laboratory','lab_test_id',1040,'HIV RAPID TEST','TESTE RÁPIDO DE HIV',''),
('laboratory','lab_test_id',23722,'LAB TEST REQUEST','PEDIDO DE EXAMES LABORATORIAIS',''),
('laboratory','result_qualitative_id',703,'POSITIVE','POSITIVO',''),
('laboratory','result_qualitative_id',664,'NEGATIVE','NEGATIVO',''),
('laboratory','result_qualitative_id',1067,'UNKNOWN','DESCONHECIDO',''),
('laboratory','result_qualitative_id',1138,'INDETERMINATE','INDETERMINADO',''),
('laboratory','result_qualitative_id',1306,'BEYOND DETECTABLE LIMIT','ALÉM DO LIMITE DETECTAVEL',''),
('laboratory','result_qualitative_id',1304,'POOR SAMPLE QUALITY','MÁ QUALIDADE DE AMOSTRA',''),
('laboratory','result_qualitative_id',23814,'UNDETECTABLE','INDETECTAVEL',''),
('laboratory','result_qualitative_id',23907,'LESS THAN 40 COPIES/ML','MENOR DE 40 COPIAS/ML',''),
('laboratory','result_qualitative_id',23905,'LESS THAN 10 COPIES/ML','MENOR DE 10 COPIAS/ML',''),
('laboratory','result_qualitative_id',23904,'LESS THAN 839 COPIES/ML','MENOR DE 839 COPIAS/ML',''),
('laboratory','result_qualitative_id',23906,'LESS THAN 20 COPIES/ML','MENOR DE 20 COPIAS/ML',''),
('laboratory','result_qualitative_id',23908,'LESS THAN 400 COPIES/ML','MENOR DE 400 COPIAS/ML',''),
('laboratory','result_qualitative_id',165331,'LESS THAN','MENOR DE',''),
('laboratory','specimen_type_id',1002,'PLASMA','PLASMA',''),
('laboratory','specimen_type_id',23831,'DRY BLOOD SPOT','AMOSTRA DE SANGUE SECO',''),
('tb_data','tb_symptom',1065,'YES','SIM',''),
('tb_data','tb_symptom',1066,'NO','NÃO',''),
('tb_data','symptom_fever',1763,'FEVER','FEBRE',''),
('tb_data','symptom_weight_loss',1764,'WEIGHT LOSS','PERDA DE PESO',''),
('tb_data','symptom_night_sweat',1762,'NIGHT SWEATS','SUORES NOCTURNOS',''),
('tb_data','symptom_cough',1760,'COUGH','TOSSE',''),
('tb_data','symptom_asthenia',23760,'ASTHENIA','Astenia',''),
('tb_data','symptom_tb_contact',1765,'TB CONTACT','CONTACTO DE TB',''),
('tb_data','symptom_adenopathy',161,'ADENOPATHY','ADENOPATIA',''),
('tb_data','tb_diagnose',1065,'YES','SIM',''),
('tb_data','tb_diagnose',1066,'NO','NÃO',''),
('tb_data','tb_treatment',1256,'START','INÍCIO',''),
('tb_data','tb_treatment',1257,'CONTINUE','CONTINUA',''),
('tb_data','tb_treatment',1267,'COMPLETED','FIM',''),
('prophylaxis','regimen_prophylaxis',656,'ISONIAZID','ISONIAZIDA',''),
('prophylaxis','regimen_prophylaxis',23954,'3HP','3HP',''),
('prophylaxis','regimen_prophylaxis',165305,'1HP','1HP',''),
('prophylaxis','regimen_prophylaxis',165306,'LFX','LFX',''),
('prophylaxis','regimen_prophylaxis',23982,'Isoniazid + Pyridoxine','Isoniazida + Piridoxina',''),
('prophylaxis','regimen_prophylaxis',23983,'Levofloxacin + Pyridoxine','Levofloxacina + Piridoxina',''),
('prophylaxis','regimen_prophylaxis',23984,'3HP + Pyridoxine','3HP + Piridoxina',''),
('prophylaxis','regimen_prophylaxis',916,'COTRIMOXAZOL','COTRIMOXAZOLE',''),
('prophylaxis','regimen_prophylaxis',165214,'TDF/3TC','TDF/3TC',''),
('prophylaxis','regimen_prophylaxis',165215,'TDF/FTC','TDF/FTC',''),
('prophylaxis','prophylaxis_status',1256,'START','INÍCIO',''),
('prophylaxis','prophylaxis_status',1257,'CONTINUE','CONTINUA',''),
('prophylaxis','prophylaxis_status',1267,'COMPLETED','FIM',''),
('prophylaxis','prophylaxis_status',1705,'RESTART','REINICIO',''),
('prophylaxis','secondary_effect',1065,'YES','SIM',''),
('prophylaxis','secondary_effect',1066,'NO','NÃO',''),
('prophylaxis','dispensation_type',1098,'MONTHLY','MENSAL',''),
('prophylaxis','dispensation_type',23720,'QUARTERLY','TRIMESTRAL',''),
('sti','sti_concept_id',6258,'SCREENING FOR STI','RASTREIO DE ITS',''),
('sti','sti_concept_id',174,'STI','ITS',''),
('sti','sti_value',1065,'YES','SIM',''),
('sti','sti_value',1066,'NO','NÃO',''),
('sti','sti_value',223,'SIFILIS','SÍFILIS',''),
('sti','sti_value',5993,'VAGINAL DISCHARGE','CORRIMENTO VAGINAL',''),
('sti','sti_value',5995,'URETHRAL DISCHARGE','CORRIMENTO URETRAL',''),
('sti','sti_value',864,'GENITAL SORES','ULCERAS GENETAIS',''),
('sti','sti_value',902,'PELVIC INFLAMMATORY DISEASE','DOENCA INFLAMATORIA PELVICA',''),
('sti','sti_value',12611,'INFLAMMATORY DISORDER OF THE SCROTUM','Transtorno inflamatório do escroto',''),
('sti','sti_value',6747,'GRANULOMA INGUINALE','Granuloma inguinal',''),
('family_planning','fp_concept_id',374,'METHOD OF FAMILY PLANNING','MÉTODO DE PLANEAMENTO FAMILIAR',''),
('family_planning','fp_method',1107,'NONE','NENHUM',''),
('family_planning','fp_method',190,'CONDOMS','PRESERVATIVO',''),
('family_planning','fp_method',780,'ORAL CONTRACEPTION','CONTRACEPTIVO ORAL',''),
('family_planning','fp_method',5279,'INJECTABLE CONTRACEPTIVES','INJECTAVEL',''),
('family_planning','fp_method',21928,'IMPLANT','IMPLANTE',''),
('family_planning','fp_method',5275,'INTRAUTERINE DEVICE','DISPOSITIVO INTRA UTERINO',''),
('family_planning','fp_method',5276,'FEMALE STERILIZATION','ESTERILIZAÇÃO FEMININA',''),
('family_planning','fp_method',23714,'VASECTOMY','VASETOMIA',''),
('family_planning','fp_method',23715,'LACTATIONAL AMENORRHEA METHOD','AMINORREIA LACTACIONAL',''),
('counseling','diagnosis_reveal',6339,'NOT REVEALED','NÃO REVELADO',''),
('counseling','diagnosis_reveal',6338,'PARTIALLY REVEALED','PARCIALMENTE REVELADO',''),
('counseling','diagnosis_reveal',6337,'REVEALED','REVELADO',''),
('counseling','hiv_disclosure',1065,'YES','SIM',''),
('counseling','hiv_disclosure',1066,'NO','NÃO',''),
('counseling','adherence_plan',1065,'YES','SIM',''),
('counseling','adherence_plan',1066,'NO','NÃO',''),
('counseling','secondary_effects',1065,'YES','SIM',''),
('counseling','secondary_effects',1066,'NO','NÃO',''),
('counseling','adherence_art',1383,'GOOD','BOM',''),
('counseling','adherence_art',1749,'RISK','RISCO',''),
('counseling','adherence_art',1385,'BAD','MAU',''),
('counseling','consultation_reason',1115,'NORMAL','NORMAL',''),
('counseling','consultation_reason',6311,'PURE ADHERENCE','FRACA ADESÃO',''),
('counseling','consultation_reason',1707,'LTFU','ABANDONO',''),
('counseling','accept_contact',1065,'YES','SIM',''),
('counseling','accept_contact',1066,'NO','NÃO',''),
('counseling','psychosocial_refusal',1956,'DOES NOT BELIEVE TEST RESULTS','NÃO ACREDITA NO RESULTADO',''),
('counseling','psychosocial_sick',1936,'PATIENT FEELS SICK','UTENTE SENTE-SE DOENTE',''),
('counseling','psychosocial_notbelieve',6186,'DOES NOT BELIEVE ARV TREATMENT','NÃO ACREDITA NO TARV',''),
('counseling','psychosocial_lotofpills',23766,'THERE ARE MANY TABLETS','SÃO MUITOS COMPRIMIDOS',''),
('counseling','psychosocial_feelbetter',23767,'FEEL BETTER','SENTE-SE MELHOR',''),
('counseling','psychosocial_lackfood',18698,'LACK OF FOOD','FALTA DE ALIMENTO',''),
('counseling','psychosocial_lacksupport',2153,'HAS LACK OF SUPPORT','FALTA DE APOIO',''),
('counseling','psychosocial_depression',207,'DEPRESSION','DEPRESSÃO',''),
('counseling','psychosocial_notreveal',2155,'NOT REVEALED HIS HIV STATUS','NÃO REVELOU O SEU DIAGNÓSTICO',''),
('counseling','psychosocial_toxicity',2015,'ARV TREATMENT SIDE EFFECTS','EFEITOS SECUNDÁRIOS DE TARV',''),
('counseling','psychosocial_lostpills',23768,'LOST / FORGOT / SHARED TABLETS','PERDEU/ESQUECEU/PARTILHOU COMPRIMIDOS',''),
('counseling','psychosocial_stigma',6436,'STIGMA','ESTIGMA',''),
('counseling','psychosocial_trasport',820,'TRANSPORT PROBLEMS','PROBLEMAS DE TRANSPORTE',''),
('counseling','psychosocial_gbv',6303,'GENDER BASED VIOLENCE','VIOLÊNCIA BASEADA NO GÉNERO',''),
('counseling','psychosocial_cultural',23769,'CULTURAL OR TRADITIONAL ASPECTS','ASPECTOS CULTURAIS OU TRADICIONAIS',''),
('counseling','psychosocial_druguse',1603,'DRUG USE','CONSUMO DE DROGA OU ALCOOL',''),
('counseling','pp1',1065,'YES','SIM',''),
('counseling','pp1',1066,'NO','NÃO',''),
('counseling','pp2',1065,'YES','SIM',''),
('counseling','pp2',1066,'NO','NÃO',''),
('counseling','pp3',1065,'YES','SIM',''),
('counseling','pp3',1066,'NO','NÃO',''),
('counseling','pp4',1065,'YES','SIM',''),
('counseling','pp4',1066,'NO','NÃO',''),
('counseling','pp5',1065,'YES','SIM',''),
('counseling','pp5',1066,'NO','NÃO',''),
('counseling','pp6',1065,'YES','SIM',''),
('counseling','pp6',1066,'NO','NÃO',''),
('counseling','pp7',1065,'YES','SIM',''),
('counseling','pp7',1066,'NO','NÃO',''),
('counseling','keypop_lubricants',1065,'YES','SIM',''),
('counseling','keypop_lubricants',1066,'NO','NÃO',''),
('prep','hiv_test_result',664,'NEGATIVE','NEGATIVO',''),
('prep','hiv_test_result',703,'POSITIVE','POSITIVO',''),
('prep','hiv_test_result',1138,'INDETERMINATE','INDETERMINADO',''),
('prep','accept_prep_start',1065,'YES','SIM',''),
('prep','accept_prep_start',1066,'NO','NÃO',''),
('prep','accept_prep_start',165288,'WILL THINK','VAI PENSAR',''),
('prep','hepb_result',664,'NEGATIVE','NEGATIVO',''),
('prep','hepb_result',703,'POSITIVE','POSITIVO',''),
('prep','hepb_result',1118,'NOT DONE','NÃO FEITO',''),
('prep','sifilis_result',664,'NEGATIVE','NEGATIVO',''),
('prep','sifilis_result',703,'POSITIVE','POSITIVO',''),
('prep','sifilis_result',1118,'NOT DONE','NÃO FEITO',''),
('prep','sti_diagnosis_leu',5993,'VAGINAL DISCHARGE','CORRIMENTO VAGINAL',''),
('prep','sti_diagnosis_ure',5995,'URETHRAL DISCHARGE','CORRIMENTO URETRAL',''),
('prep','sti_diagnosis_gen',864,'GENITAL SORES','ULCERAS GENETAIS',''),
('prep','sti_diagnosis_pel',902,'PELVIC','DOENCA INFLAMATORIA PELVICA',''),
('prep','sti_diagnosis_inf',12611,'Inflammatory disorder of the scrotum','Transtorno inflamatório do escroto',''),
('prep','sti_diagnosis_gra',6747,'Granuloma inguinale','Granuloma inguinal',''),
('prep','sti_diagnosis_other',165208,'STI - OTHER RESULT','ITS - OUTROS',''),
('prep','regimen_prophylaxis_prep',165214,'TDF/3TC','TDF/3TC',''),
('prep','regimen_prophylaxis_prep',165215,'TDF/FTC','TDF/FTC',''),
('prep','dsd_prep',23730,'QUARTERLY DISPENSATION','DISPENSA TRIMESTRAL',''),
('prep','dsd_prep',23888,'SEMESTER DISPENSATION','DISPESNSA SEMESTRAL',''),
('prep','dsd_prep',165316,'HOURS EXTENSION','EXTENSÃO DE HORÁRIO',''),
('prep','dsd_prep',23729,'RAPID FLOW','FLUXO RÁPIDO',''),
('prep','dsd_prep',165264,'MOBILE BRIGADES','BRIGADAS MÓVEIS',''),
('prep','dsd_prep',165265,'MOBILE CLINICS','CLÍNICAS MÓVEIS',''),
('prep','key_vulnerable_msm',137,'Men who have sex with Men','HOMEN QUE FAZ SEXO COM HOMEN',''),
('prep','key_vulnerable_drug',20454,'DRUG USE','USUARIO DE DROGA',''),
('prep','key_vulnerable_sw',1901,'SEX WORKER','TRABALHADOR DE SEXO',''),
('prep','key_vulnerable_prison',20426,'IMPRISONMENT AND OTHER INCARCERATION','RECLUSO',''),
('prep','key_vulnerable_ayr',165287,'Adolescents and Youth at Risk','ADOLESCENTES E JOVENS EM RISCO',''),
('prep','key_vulnerable_police',1902,'MILITARY/POLICE','MILITAR/POLÍCIA',''),
('prep','key_vulnerable_miner',1908,'MINER','MINEIRO',''),
('prep','key_vulnerable_driver',1903,'DRIVER','MOTORISTA',''),
('prep','key_vulnerable_serodiscordant',1995,'COUPLES RESULTS ARE DIFFERENT','CASAIS SERODESCORDANTES',''),
('prep','key_vulnerable_pregnant',1982,'PREGNANT','GRÁVIDA',''),
('prep','key_vulnerable_lactant',6332,'LACTANT','LACTANTE',''),
('prep','key_vulnerable_other',5622,'OTHER','OUTRO',''),
('prep','renal_failure_signs',1065,'YES','SIM',''),
('prep','renal_failure_signs',1066,'NO','NÃO',''),
('prep','adherence_counseling',1065,'YES','SIM',''),
('prep','adherence_counseling',1066,'NO','NÃO',''),
('prep','condom_offer',1065,'YES','SIM',''),
('prep','condom_offer',1066,'NO','NÃO',''),
('prep','pregnant',1065,'YES','SIM',''),
('prep','pregnant',1066,'NO','NÃO',''),
('prep','lactant',1065,'YES','SIM',''),
('prep','lactant',1066,'NO','NÃO',''),
('prep','prep_interrupted_hivpos',1169,'HIV POSTIVE','HIV POSITIVO',''),
('prep','prep_interrupted_sideeffect',2015,'ARV TREATMENT SIDE EFFECTS','EFEITOS SECUNDÁRIOS DE TARV',''),
('prep','prep_interrupted_norisk',165226,'NO MORE SUBSTANTIAL RISKS','SEM MAIS RISCOS',''),
('prep','prep_interrupted_userrequest',165227,'USER PREFERENCE','PREFERENCIA DO UTENTE',''),
('prep','prep_interrupted_other',5622,'OTHER','OUTRO',''),
('dah','tarv_status',1256,'START','INÍCIO',''),
('dah','tarv_status',1705,'RESTART','REINICIO ',''),
('dah','tarv_status',6276,'ART','TARV',''),
('dah','tarv_status',6275,'PRE-ART','PRE-TARV',''),
('dah','tarv_line',21150,'FIRST LINE','PRIMEIRA LINHA',''),
('dah','tarv_line',21148,'SECOND LINE','SEGUNDA LINHA',''),
('dah','tarv_line',21149,'THIRD LINE','TERCEIRA LINHA',''),
('dah','tarv_regimen',1703,'AZT+3TC+EFV','AZT+3TC+EFV',''),
('dah','tarv_regimen',6100,'AZT+3TC+LPV/r','AZT+3TC+LPV/r',''),
('dah','tarv_regimen',1651,'AZT+3TC+NVP','AZT+3TC+NVP',''),
('dah','tarv_regimen',6324,'TDF+3TC+EFV','TDF+3TC+EFV',''),
('dah','tarv_regimen',6104,'ABC+3TC+EFV','ABC+3TC+EFV',''),
('dah','tarv_regimen',23784,'TDF+3TC+DTG','TDF+3TC+DTG',''),
('dah','tarv_regimen',23785,'TDF+3TC+DTG','TDF+3TC+DTG',''),
('dah','tarv_regimen',23786,'ABC+3TC+DTG','ABC+3TC+DTG',''),
('dah','tarv_regimen',6116,'AZT+3TC+ABC','AZT+3TC+ABC',''),
('dah','tarv_regimen',6106,'ABC+3TC+LPV/r','ABC+3TC+LPV/r',''),
('dah','tarv_regimen',6105,'ABC+3TC+NVP','ABC+3TC+NVP',''),
('dah','tarv_regimen',6108,'TDF+3TC+LPV/r','TDF+3TC+LPV/r',''),
('dah','tarv_regimen',6424,'TDF+3TC+LPV/r','TDF+3TC+LPV/r',''),
('dah','tarv_regimen',23790,'TDF+3TC+LPV/r+RTV','TDF+3TC+LPV/r+RTV',''),
('dah','tarv_regimen',23791,'TDF+3TC+ATV/r','TDF+3TC+ATV/r',''),
('dah','tarv_regimen',23792,'ABC+3TC+ATV/r','ABC+3TC+ATV/r',''),
('dah','tarv_regimen',23793,'AZT+3TC+ATV/r','AZT+3TC+ATV/r',''),
('dah','tarv_regimen',23795,'ABC+3TC+ATV/r+RAL','ABC+3TC+ATV/r+RAL',''),
('dah','tarv_regimen',23796,'TDF+3TC+ATV/r+RAL','TDF+3TC+ATV/r+RAL',''),
('dah','tarv_regimen',23801,'AZT+3TC+RAL','AZT+3TC+RAL',''),
('dah','tarv_regimen',23802,'AZT+3TC+DRV/r','AZT+3TC+DRV/r',''),
('dah','tarv_regimen',23815,'AZT+3TC+DTG','AZT+3TC+DTG',''),
('dah','tarv_regimen',6329,'TDF+3TC+RAL+DRV/r','TDF+3TC+RAL+DRV/r',''),
('dah','tarv_regimen',23797,'ABC+3TC+DRV/r+RAL','ABC+3TC+DRV/r+RAL',''),
('dah','tarv_regimen',23798,'3TC+RAL+DRV/r','3TC+RAL+DRV/r',''),
('dah','tarv_regimen',23803,'AZT+3TC+RAL+DRV/r','AZT+3TC+RAL+DRV/r',''),
('dah','tarv_regimen',6243,'TDF+3TC+NVP','TDF+3TC+NVP',''),
('dah','tarv_regimen',6103,'D4T+3TC+LPV/r','D4T+3TC+LPV/r',''),
('dah','tarv_regimen',792,'D4T+3TC+NVP','D4T+3TC+NVP',''),
('dah','tarv_regimen',1827,'D4T+3TC+EFV','D4T+3TC+EFV',''),
('dah','tarv_regimen',6102,'D4T+3TC+ABC','D4T+3TC+ABC',''),
('dah','tarv_regimen',1311,'ABC+3TC+LPV/r','ABC+3TC+LPV/r',''),
('dah','tarv_regimen',1312,'ABC+3TC+NVP','ABC+3TC+NVP',''),
('dah','tarv_regimen',1313,'ABC+3TC+EFV','ABC+3TC+EFV',''),
('dah','tarv_regimen',1314,'AZT+3TC+LPV/r','AZT+3TC+LPV/r',''),
('dah','tarv_regimen',1315,'TDF+3TC+EFV','TDF+3TC+EFV',''),
('dah','tarv_regimen',6330,'AZT+3TC+RAL+DRV/r','AZT+3TC+RAL+DRV/r',''),
('dah','tarv_regimen',6325,'D4T+3TC+ABC+LPV/r','D4T+3TC+ABC+LPV/r',''),
('dah','tarv_regimen',6326,'AZT+3TC+ABC+LPV/r','AZT+3TC+ABC+LPV/r',''),
('dah','tarv_regimen',6327,'D4T+3TC+ABC+EFV','D4T+3TC+ABC+EFV',''),
('dah','tarv_regimen',6328,'AZT+3TC+ABC+EFV','AZT+3TC+ABC+EFV',''),
('dah','tarv_regimen',6109,'AZT+DDI+LPV/r','AZT+DDI+LPV/r',''),
('dah','tarv_regimen',21163,'AZT+3TC+LPV/r','AZT+3TC+LPV/r',''),
('dah','tarv_regimen',23799,'TDF+3TC+DTG','TDF+3TC+DTG',''),
('dah','tarv_regimen',23800,'ABC+3TC+DTG','ABC+3TC+DTG',''),
('dah','tarv_regimen',6110,'D4T20+3TC+NVP','D4T20+3TC+NVP',''),
('dah','tarv_regimen',1702,'AZT+3TC+NFV','AZT+3TC+NFV',''),
('dah','tarv_regimen',817,'AZT+3TC+ABC','AZT+3TC+ABC',''),
('dah','tarv_regimen',6244,'AZT+3TC+RTV','AZT+3TC+RTV',''),
('dah','tarv_regimen',1700,'AZT+DDl+NFV','AZT+DDl+NFV',''),
('dah','tarv_regimen',633,'EFV','EFV',''),
('dah','tarv_regimen',625,'D4T','D4T',''),
('dah','tarv_regimen',631,'NVP','NVP',''),
('dah','tarv_regimen',628,'3TC','3TC',''),
('dah','tarv_regimen',635,'NFV','NFV',''),
('dah','tarv_regimen',797,'AZT','AZT',''),
('dah','tarv_regimen',814,'ABC','ABC',''),
('dah','tarv_regimen',6107,'TDF+AZT+3TC+LPV/r','TDF+AZT+3TC+LPV/r',''),
('dah','tarv_regimen',6236,'D4T+DDI+RTV-IP','D4T+DDI+RTV-IP',''),
('dah','tarv_regimen',1701,'ABC+DDI+NFV','ABC+DDI+NFV',''),
('dah','tarv_regimen',6114,'3DFC','3DFC',''),
('dah','tarv_regimen',6115,'DFC+EFV','DFC+EFV',''),
('dah','tarv_regimen',6233,'AZT+3TC+DDI+LPV','AZT+3TC+DDI+LPV',''),
('dah','tarv_regimen',6234,'ABC+TDF+LPV','ABC+TDF+LPV',''),
('dah','tarv_regimen',6242,'D4T+DDI+NVP','D4T+DDI+NVP',''),
('dah','tarv_regimen',6118,'DI50+ABC+LPV','DI50+ABC+LPV',''),
('dah','tarv_regimen',23787,'ABC+AZT+LPV/r','ABC+AZT+LPV/r',''),
('dah','tarv_regimen',5424,'OTHER','OUTRO',''),
('dah','who_stage',1204,'I','I',''),
('dah','who_stage',1205,'II','II',''),
('dah','who_stage',1206,'III','III',''),
('dah','who_stage',1207,'IV','IV',''),
('dah','exit_criteria_nocondition',165414,'NO ACTIVE CLINICAL CONDITION','SEM CONDIÇÃO CLÍNICA ACTIVA',''),
('dah','exit_criteria_cvsupressed',165382,'SUPPRESSED VIRAL LOAD','CARGA VIRAL SUPRIMIDA ',''),
('dah','exit_criteria_cd4',165383,'CD4 ≥ 100 cells/ml','CD4 ≥ 100 cells/ml',''),
('dah','exit_criteria_',165384,'NO NEED FOR FLUCONAZOLE PROPHYLAXIS','SEM NECESSIDADE DE PROFILAXIA COM FLUCONAZOL','')
